### ISSUE TITLE
Level:high warning on api gateway despite alternative auth settings

### ISSUE THREAD

**Issue by blair55** [Skyscanner/LambdaGuard#13]
Thanks for publishing a great tool! We've been using it and have a question/feedback:

We have some functions invoked by api-gateway. In one case, a method has Authorization: IAM enabled. In another case, the method has API Key: Required.

Both of these functions incur the `HIGH | Service is publicly accessible due to missing Resource-based policy` warning.

However, an APIGW with a resource policy such as the one below, does not incur the same warning.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::1234567890:root"
            },
            "Action": "execute-api:Invoke"
        }
    ]
}
```

Is there a difference between a broad-scoped resource policy on the APIGW like this and using `Authorization: AWS_IAM` at the method level? 
![image](https://user-images.githubusercontent.com/702272/68720009-cd47d100-05a5-11ea-9303-0907e83135c3.png)

**Comment by adeptex** [comment]
hey @blair55 thanks for flagging this. Will investigate and get back to you

**Comment by adeptex** [comment]
Hi @blair55, I've finally addressed the issue here: https://github.com/Skyscanner/LambdaGuard/pull/17

Closing this for now, but feel free to re-open if it doesn't completely solve the problem. Cheers!
