### ISSUE TITLE
Using get_function_configuration instead of get_function

### ISSUE THREAD

**Issue by nimrodkor** [Skyscanner/LambdaGuard#16]
Hi!

I'm looking through this project - it is super cool!
However, I experienced some permissions issues. When diving deeper, I found out it's using the method `get_function` - when my permissions are for `get_function_configuration` only. I checked - and most of the value can still be received from calling the less intrusive `get_function_configuration`. 

If you'd like, I can open a PR for it. I think it would be useful to other audits / scans of the account.

WDYT?

**Comment by adeptex** [comment]
Hey @nimrodkor, again sorry for late response. Of course PR is welcome! :)

Please make sure to follow https://github.com/Skyscanner/LambdaGuard/blob/master/CONTRIBUTING.md 

Closing this issue as I think this answers your question. Feel free to reopen if needed!

Cheers
