### ISSUE TITLE
Security stats not showing on HTML report using --input

### ISSUE THREAD

**Issue by madchap** [Skyscanner/LambdaGuard#2]
Hi,

Installed via `pip3 --user install lambdaguard`.

Running `lambdaguard --function <function_arn> --verbose` works fine.

However, putting a bunch of functions in a text file, and running `lambdaguard --input arns.txt --verbose` does not generate the proper HTML report. The `security.json` file is fine and has all the information expected, however. 

The security info does not show neither in the top level stats, nor when drilling through in the individual function. It is blank.

**Comment by adeptex** [comment]
Hi @madchap thanks for raising this. Will have a look

**Comment by adeptex** [comment]
@madchap I was not able to reproduce the issue in v2.2.0. Please update and try again.
