### ISSUE TITLE
LambdaGuard doesn't support running in multi-region

### ISSUE THREAD

**Issue by nimrodkor** [Skyscanner/LambdaGuard#20]
Currently, region is one of the parameters inputted, with the default being `eu-west-1` . I think a better approach is if region isn't specified - scan all available regions.
I think a list which covers most of the cases can be created statically, and a dynamic list can probably be queried somehow.

**Comment by adeptex** [comment]
Hey @nimrodkor good idea! Will see to add it in the future release

**Comment by adeptex** [comment]
This will be added once https://github.com/Skyscanner/LambdaGuard/pull/25 is merged 

Cheers and thanks for the contribution @nimrodkor
