### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'arn'

### ISSUE THREAD

**Issue by efkay88** [Skyscanner/LambdaGuard#27]
Hi,

I'm getting the following issue: AttributeError: 'NoneType' object has no attribute 'arn'
This is how the arn looks like:
arn:aws:lambda:eu-central-1:1234:function:myfunction

or even 
./lambdaguard --function arn:aws:lambda:eu-central-1:1234:function:*

provides the same error. 

Any idea what I'm missing?

Cheers!

**Comment by adeptex** [comment]
hey @efkay88 sorry for late reply. Thanks for raising this, I will have a look.

**Comment by adeptex** [comment]
Should be fixed by this commit https://github.com/Skyscanner/LambdaGuard/commit/ed323c9bc00b1941e0743f2d450a6ac85124fdb4

Please feel free to create another issue if this does not completely solve the problem. Cheers!
