### ISSUE TITLE
Lambdaguard with Sonarqube : Require documentation

### ISSUE THREAD

**Issue by amitmalhotra-cell** [Skyscanner/LambdaGuard#34]
hi @adeptex  ,

I want to do static code analysis of lambda function code using sonarqube. 
All I found was below link which gives a brief about using lambdaguard with sonarqube.
https://github.com/Skyscanner/LambdaGuard/blob/master/README.md

**Is there any detail documentation with example for the same ?**

**Comment by Leectan** [comment]
Same here, looks like there is nothing returned after running lambdaguard --sonarqube config.json

**Comment by adeptex** [comment]
Hi all, thanks for reporting. I've update SQ - https://github.com/Skyscanner/LambdaGuard/pull/36
The problem should now be fixed. Please feel free to open another issue if you are still not getting any SQ results.
