### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by ryryfasch** [Skyscanner/LambdaGuard#37]
I have tried to install Lambdaguard locally on my Mac running Catalina 10.15.7. The download from worked fine, but I get "zsh: command not found: lambdaguard" every time I try to run it. I attempted to install using the "sudo make install" command from the Github repo, but still the command is not found in my terminal. Am I missing something here?

**Comment by adeptex** [comment]
Hey @ryryfasch, try like this: `sudo pip3 install lambdaguard`

**Comment by ryryfasch** [comment]
I did try that with no luck. Might it have something to do with the PATH variable?

**Comment by adeptex** [comment]
I am not able to reproduce your error on Catalina 10.15.7. 

This should work universally across all systems:
```
python3 -m venv test
. test/bin/activate
pip3 install lambdaguard
```
