### ISSUE TITLE
Issue running Sonarqube on Apple's M1 chip

### ISSUE THREAD

**Issue by jankal13** [Skyscanner/LambdaGuard#38]
Although Docker does already support the Apple M1 chip, Sonarqube does apparently not: https://github.com/SonarSource/docker-sonarqube/issues/475

This also results in an error message when trying to run "make sonarqube". However, the issue can be bypassed through the usage of the [this](https://github.com/SonarSource/docker-sonarqube/issues/475#issuecomment-819119876) adjusted sonarqube docker and some adjustments to the [dockerfile](https://github.com/mrzyte/LambdaGuard/blob/arm64/SonarQube.Dockerfile). 

Best regards

**Comment by adeptex** [comment]
hey @mrzyte, as per https://github.com/SonarSource/docker-sonarqube/issues/475#issuecomment-790434225 please create a feature request in SQ community forums.

regards
