### ISSUE TITLE
`make aws` fails with 'aws/iam-user.json'

### ISSUE THREAD

**Issue by delta-sine** [Skyscanner/LambdaGuard#6]
Hi, I get the following error when I run `make aws`:

An error occurred (ValidationError) when calling the CreateChangeSet operation: Template format error: Outputs name 'aws_access_key_id' is non alphanumeric.

I have valid keys defined in ~/.aws/credentials

thanks

**Comment by adeptex** [comment]
Hi @delta-sine, thanks for reporting this. Will take a look

**Comment by adeptex** [comment]
Fixed in https://github.com/Skyscanner/LambdaGuard/commit/cb73926a2daf6303a7b2492f68a1d2587fc9ba50
