### ISSUE TITLE
IAM permissions

### ISSUE THREAD

**Issue by devhops** [Skyscanner/LambdaGuard#9]
Hi,

I'd like to run this on it's own instance as part of my security tooling.

It would be really useful to know which IAM permissions LambdaGuard needs to run, so I can create the relevant instance profile.

Thanks :)

**Comment by adeptex** [comment]
Hi @devhops you can use `make aws` to setup AWS access. Here's what it will do - https://github.com/Skyscanner/LambdaGuard/blob/master/aws/iam-user.json

I went the lazy way and just used `arn:aws:iam::aws:policy/ReadOnlyAccess` to accommodate any new checks that will be integrated. If you don't want this, you'd have to define specific permissions for each AWS service that is accessed by LambdaGuard. You can check currently implemented services here: https://github.com/Skyscanner/LambdaGuard/tree/master/lambdaguard/core
